package com.fourninja.goblin.model.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Agent generated by hbm2java
 */
@Entity
@Table(name="agent"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="agent_code") 
)
public class Agent  implements java.io.Serializable {


     private Long id;
     private Address address;
     private AgentType agentType;
     private Country country;
     private User user;
     private String agentCode;
     private String name;
     private String idNumber;
     private String email;
     private String phoneNumber;
     private boolean onlineMode;
     private String createdBy;
     private Date createdAt;
     private String updatedBy;
     private Date updatedAt;
     private boolean actFlag;

    public Agent() {
    }

	
    public Agent(boolean onlineMode, boolean actFlag) {
        this.onlineMode = onlineMode;
        this.actFlag = actFlag;
    }
    public Agent(Address address, AgentType agentType, Country country, User user, String agentCode, String name, String idNumber, String email, String phoneNumber, boolean onlineMode, String createdBy, Date createdAt, String updatedBy, Date updatedAt, boolean actFlag) {
       this.address = address;
       this.agentType = agentType;
       this.country = country;
       this.user = user;
       this.agentCode = agentCode;
       this.name = name;
       this.idNumber = idNumber;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.onlineMode = onlineMode;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.updatedBy = updatedBy;
       this.updatedAt = updatedAt;
       this.actFlag = actFlag;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="address_id")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="agent_type_id")
    public AgentType getAgentType() {
        return this.agentType;
    }
    
    public void setAgentType(AgentType agentType) {
        this.agentType = agentType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="phone_code")
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="agent_code", unique=true, length=50)
    public String getAgentCode() {
        return this.agentCode;
    }
    
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="id_number", length=12)
    public String getIdNumber() {
        return this.idNumber;
    }
    
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone_number", length=20)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="online_mode", nullable=false)
    public boolean isOnlineMode() {
        return this.onlineMode;
    }
    
    public void setOnlineMode(boolean onlineMode) {
        this.onlineMode = onlineMode;
    }

    
    @Column(name="created_by", length=50)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=29)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    
    @Column(name="updated_by", length=50)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=29)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="act_flag", nullable=false)
    public boolean isActFlag() {
        return this.actFlag;
    }
    
    public void setActFlag(boolean actFlag) {
        this.actFlag = actFlag;
    }




}


