package com.fourninja.goblin.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
    ,schema="public"
)
public class Country  implements java.io.Serializable {


     private Long id;
     private String sortname;
     private String name;
     private Long phonecode;
     private Set<State> states = new HashSet<State>(0);
     private Set<Address> addresses = new HashSet<Address>(0);
     private Set<Agent> agents = new HashSet<Agent>(0);

    public Country() {
    }

    public Country(String sortname, String name, Long phonecode, Set<State> states, Set<Address> addresses, Set<Agent> agents) {
       this.sortname = sortname;
       this.name = name;
       this.phonecode = phonecode;
       this.states = states;
       this.addresses = addresses;
       this.agents = agents;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="sortname", length=3)
    public String getSortname() {
        return this.sortname;
    }
    
    public void setSortname(String sortname) {
        this.sortname = sortname;
    }

    
    @Column(name="name", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="phonecode")
    public Long getPhonecode() {
        return this.phonecode;
    }
    
    public void setPhonecode(Long phonecode) {
        this.phonecode = phonecode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<State> getStates() {
        return this.states;
    }
    
    public void setStates(Set<State> states) {
        this.states = states;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Agent> getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set<Agent> agents) {
        this.agents = agents;
    }




}


