package com.fourninja.goblin.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class Product  implements java.io.Serializable {


     private Long id;
     private String code;
     private String name;
     private Long productTypeId;
     private Double basePrice;

    public Product() {
    }

    public Product(String code, String name, Long productTypeId, Double basePrice) {
       this.code = code;
       this.name = name;
       this.productTypeId = productTypeId;
       this.basePrice = basePrice;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="code", unique=true, length=12)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="product_type_id")
    public Long getProductTypeId() {
        return this.productTypeId;
    }
    
    public void setProductTypeId(Long productTypeId) {
        this.productTypeId = productTypeId;
    }

    
    @Column(name="base_price", scale=0)
    public Double getBasePrice() {
        return this.basePrice;
    }
    
    public void setBasePrice(Double basePrice) {
        this.basePrice = basePrice;
    }




}


