package com.fourninja.goblin.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductType generated by hbm2java
 */
@Entity
@Table(name="product_type"
    ,schema="public"
)
public class ProductType  implements java.io.Serializable {


     private Long id;
     private String description;
     private String createdBy;
     private Date createdAt;
     private String updatedBy;
     private Date updatedAt;
     private boolean actFlag;
     private Set<Product> products = new HashSet<Product>(0);

    public ProductType() {
    }

	
    public ProductType(boolean actFlag) {
        this.actFlag = actFlag;
    }
    public ProductType(String description, String createdBy, Date createdAt, String updatedBy, Date updatedAt, boolean actFlag, Set<Product> products) {
       this.description = description;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.updatedBy = updatedBy;
       this.updatedAt = updatedAt;
       this.actFlag = actFlag;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="description", length=30)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="created_by", length=50)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=29)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    
    @Column(name="updated_by", length=50)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=29)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="act_flag", nullable=false)
    public boolean isActFlag() {
        return this.actFlag;
    }
    
    public void setActFlag(boolean actFlag) {
        this.actFlag = actFlag;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productType")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


